image: docker:19.03
services:
  - docker:19.03-dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  image: mwienk/docker-git-ftp

  script:
    - git config git-ftp.url "${FTP_HOSTNAME}"
    - git config git-ftp.user "${FTP_USERNAME}"
    - git config git-ftp.password "${FTP_PASSWORD}"
    # - git ftp init
    # - git ftp catchup
    # - git ftp push --commit main
    - git ftp push
#   after_script:
#     - *after_script
